typeidea/typeidea/urls.py
from django.contrib import admin
from django.urls import path,re_path
from django.contrib.sitemaps import views as sitemap_views
from .custom_site import custom_site
from blog.views import (
    IndexView,CategoryView,
    TagView,PostDetailView,
    SearchView,AuthorView,
)
from config.views import LinkListView
from comment.views import CommentView
from blog.rss import LatestPostFeed
from blog.sitemap import PostSitemap




urlpatterns = [
    path('super_admin/', admin.site.urls,name='super-admin'),  #用户相关的
    path('admin/',custom_site.urls,name='admin'),        #业务相关的
    re_path(r'^$',IndexView.as_view(),name='index'),
    re_path(r'search/',SearchView.as_view(),name='search'),
    re_path(r'author/(?P<owner_id>\d+)/$',AuthorView.as_view(),name='author'),
    re_path(r'^category/(?P<category_id>\d+)/$',CategoryView.as_view(),name='category-list'),    #(?P<name>pattern)分组命名
    re_path(r'^tag/(?P<tag_id>\d+)/$',TagView.as_view(),name='tag-list'),
    re_path(r'^post/(?P<post_id>\d+).html$',PostDetailView.as_view(),name='post-detail'),
    re_path(r'^links/$',LinkListView.as_view(),name='links'),
    re_path(r'^comment/$',CommentView.as_view(),name='comment'),
    re_path(r'^rss|feed/',LatestPostFeed(),name='rss'),
    re_path(r'^sitemap\.xml$',sitemap_views.sitemap,{'sitemaps':{'posts':PostSitemap}})

]

typeidea/comment/models.py
from django.db import models
from blog.models import Post

class Comment(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
    )

    target = models.CharField(max_length=200,verbose_name='评论目标')
    content = models.CharField(max_length=2000,verbose_name='内容')
    nickname = models.CharField(max_length=50,verbose_name='昵称')
    website = models.URLField(verbose_name='网站')
    email = models.EmailField(verbose_name='邮箱')
    status = models.PositiveIntegerField(default=STATUS_NORMAL,choices=STATUS_ITEMS,
                                         verbose_name='状态')
    created_time = models.DateTimeField(auto_now_add=True,verbose_name='创建时间')

    class Meta:
        verbose_name = verbose_name_plural = '评论'

    @classmethod
    def get_by_target(cls,target):
        return cls.objects.filter(target=target,status=cls.STATUS_NORMAL)

typeidea/comment/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    """评论表单"""
    nickname = forms.CharField(
        label='昵称',
        max_length=50,
        widget=forms.widgets.Input(
            attrs={'class':'form-control','style':"width:20%;"}
        )
    )
    email = forms.CharField(
        label='邮箱',
        max_length=50,
        widget=forms.widgets.EmailInput(
            attrs={'class': 'form-control', 'style': "width:20%;"}
        )
    )
    website = forms.CharField(
        label = '网站',
        max_length=100,
        widget=forms.widgets.URLInput(
            attrs={'class': 'form-control', 'style': "width:20%;"}
        )
    )
    content = forms.CharField(
        label='内容',
        max_length=500,
        widget=forms.widgets.Textarea(
            attrs={'rows':6,'cols':60,'class':'form-control'}
        )
    )
    def clean_content(self):
        import mistune #导入Markdown插件
        """对评论内容做校验"""
        content = self.cleaned_data.get('content')


        if len(content) < 10:
            raise forms.ValidationError('评论内容太短了！')

        content = mistune.markdown(content)  # 保存数据之前进行格式化
        return content

    class Meta:
        model = Comment
        fields = ['target','nickname','email','website','content']

typeidea/comment/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.views.generic import TemplateView
from .forms import CommentForm


class CommentView(TemplateView):
    """评论视图"""
    http_method_names = ['post']
    template_name = 'comment/result.html'

    def post(self, request, *args, **kwargs):
        comment_form = CommentForm(request.POST)
        target = request.POST.get('target')
        print('target......')

        if comment_form.is_valid():
            instance = comment_form.save(commit=False)
            instance.target = target
            instance.save()
            successed = True
            # return redirect(target)
        else:
            successed = False

        context = {
            'successed': successed,
            'form': comment_form,
            'target': target,
        }
        return self.render_to_response(context)

typeidea/typeidea/themes/default/templates/comment/block.html
<hr/>
<h4>评论</h4>
<div class="comment">
    <form class="form-group" action="{% url 'comment' %}" method="POST">
        {% csrf_token %}
        {{ comment_form }}
        <input type="submit" value="写好了">
    </form>
    <h4>评论列表</h4>
    <ul class="list-group">
        {% for comment in comment_list %}
        <li class="list-group-item">
            <div class="nickname">
                <a href="{{ comment.website }}">{{ comment.nickname }}</a>

                <span>{{ comment.created_time }}</span>

            </div>
            <div class="comment-content">
                {% autoescape off %}    <!--关闭转码功能-->
                {{ comment.content }}
                {% endautoescape %}
            </div>
        </li>
        {% endfor %}
    </ul>
</div>

typeidea/typeidea/themes/default/templates/comment/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>评论结果页</title>
    <style>
        body {
            TEXT-ALIGN: center;}
        .result {
            text-align: center;
            width: 40%;
            margin: auto;
        }
        .errorlist {
            color: red;
        }
        ul li {
            list-style-type: None;
        }
    </style>
</head>
<body>
<div class="result">
    {% if successed %}
        评论成功！
        <a href="{{ target }}">返回</a>
    {% else %}
        <ul class="errorlist">
            {% for field,message in form.errors.items %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        <a href="javascript:window.history.back();">返回</a>
    {% endif %}
</div>
</body>
</html>